server:
  port: ${SERVER_PORT:8010}
spring:
  application:
    name: ClearSolutionsTestTask
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api
api:
  validation:
    user:
      min-age: 18